version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    volumes:
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14 
    shm_size: '1gb'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  loan-application:
    image: silver3456/upgrade-selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSWER=chrome
      - HUB_HOST=hub
      - MODULE=loan-application.xml  
    volumes:
      - ./test-results:/usr/share/upgrade/test-output
  
  